# Generated by Django 3.2.5 on 2021-09-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('leaves_category', models.CharField(choices=[('Dry Tea Leaves', 'Dry Tea Leaves'), ('Light Tea Leaves', 'Light Tea Leaves')], max_length=20, null=True)),
                ('in_date', models.DateField(null=True)),
                ('in_time', models.TimeField(null=True)),
                ('tray_id', models.CharField(max_length=10000, null=True)),
                ('temparature', models.FloatField(null=True)),
                ('tea_weight', models.PositiveIntegerField(null=True)),
                ('out_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_category', models.CharField(choices=[('Tea Powder Packets', 'Tea Powder Packets'), ('Tea Leaves Jars', 'Tea Leaves Jars'), ('Tea Bags', 'Tea Bags')], max_length=20, null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventory Order',
            },
        ),
    ]
